export const data = [
  {
    id: 0,
    nome_receita: "CUPCAKE DE BATATA",
    tempo_de_preparo: "25 MIN",
    rendimento: "6 PORÇÕES",
    autor: "TUDOGOSTOSO",
    url_receita:
      "https://www.tudogostoso.com.br/receita/316950-cupcake-de-batata.html",
  },
  {
    id: 1,
    nome_receita: "CUPCAKE DE MERENGUE",
    tempo_de_preparo: "45 MIN",
    rendimento: "1 PORÇÕES",
    autor: "TUDOGOSTOSO",
    url_receita:
      "https://www.tudogostoso.com.br/receita/316950-cupcake-de-batata.html",
  },
  {
    id: 2,
    nome_receita: "CUPCAKE DE RAPARIGA",
    ingredientes: {
      DEFAULT: [
        "1,5 litro de água",
        "1 kg de batata inglesa",
        "2 colheres (sopa) de sal",
        "1 colher (sopa) de manteiga",
        "2 colheres (sopa) de amido de milho",
        "salsinha a gosto",
        "1 cebola",
        "2 dentes de alho",
        "100 g de bacon",
        "400 g de carne moída",
        "1 tomate",
        "200 g de queijo parmesão",
        "100 g de queijo mussarela",
      ],
      MACARRA0: [
        "1,5 litro de água",
        "1 kg de batata inglesa",
        "2 colheres (sopa) de sal",
        "1 colher (sopa) de manteiga",
        "2 colheres (sopa) de amido de milho",
        "salsinha a gosto",
        "1 cebola",
        "2 dentes de alho",
        "100 g de bacon",
        "400 g de carne moída",
        "1 tomate",
        "200 g de queijo parmesão",
        "100 g de queijo mussarela",
      ],
    },
    passos: {
      DEFAULT: [
        "Em uma panela, coloque água, as batatas e o sal ",
        "Deixe cozinhar muito bem, para que as batatas fiquem em ponto macio (de purê)",
        "Retire da panela e coloque em um recipiente ",
        "Junte a manteiga, o amido e o sal",
        "Amasse e misture tudo muito bem ",
        "Junte a salsinha e misture novamente ",
        "Forme pequenas bolinhas, com as mãos, dessa mistura de batata",
        "Em uma frigideira, coloque o azeite",
        "Junte a cebola, a alho e o bacon e deixe dourar bastante",
        "Junte a carne moída",
        "Coloque o sal, frite bastante a carne e adicione o tomate",
        "Coloque as bolinhas de batata reservadas em uma forma",
        "Com a mão, faça um espaço no meio delas",
        "Coloque o queijo parmesão, a carne e o queijo mussarela ",
        "Leve a airfryer por 25 minutos a 110° C ",
      ],
    },
    tempo_de_preparo: "25 MIN",
    rendimento: "6 PORÇÕES",
    autor: "TUDOGOSTOSO",
    url_receita:
      "https://www.tudogostoso.com.br/receita/316950-cupcake-de-batata.html",
  },
  {
    id: 3,
    nome_receita: "PANQUECA DE CARNE MOÍDA",
    ingredientes: {
      MASSA: [
        "1 e 1/2 xícara (chá) de farinha de trigo",
        "1 xícara (chá) de leite",
        "2 ovos",
        "4 colheres (sopa) de óleo",
        "sal a gosto",
      ],
      RECHEIO: [
        "300 g de carne moída",
        "2 colheres (sopa) de cebola picada ou ralada",
        "1/2 tomate cortado em cubos",
        "1/2 lata de extrato de tomate",
        "1 caixa de creme de leite",
        "sal a gosto",
        "400 g de muçarela fatiada",
        "queijo ralado a gosto",
      ],
    },
    passos: {
      MASSA: [
        "Bata no liquidificador os ovos, o leite, o óleo, e acrescente a farinha de trigo aos poucos.",
        "Após acrescentar toda a farinha de trigo, adicione sal a gosto.",
        "Misture a massa até obter uma consistência cremosa.",
        "Com um papel-toalha, espalhe óleo por toda a frigideira e despeje uma concha de massa.",
        "Faça movimentos circulares para que a massa se espalhe por toda a frigideira.",
        "Espere até a massa soltar do fundo e vire-a para fritar do outro lado.",
      ],
      RECHEIO: [
        "Em uma panela, doure a cebola com o óleo e acrescente a carne.",
        "Deixe cozinhar até que saia água da carne, diminua o fogo e tampe.",
        "Acrescente o tomate picado e tampe novamente.",
        "Deixe cozinhar por mais 3 minutos e misture.",
        "Acrescente o extrato de tomate e temperos a gosto.",
        "Deixe cozinhar por mais 10 minutos.",
        "Quando o molho engrossar, desligue o fogo.",
        "Deixe esfriar o molho, acrescente o creme de leite e misture bem.",
        "Quando estiver bem homogêneo, leve novamente ao fogo e deixe cozinhar em fogo baixo por mais 5 minutos.",
      ],
      MONTAGEM: [
        "Recheie a panqueca com uma fatia de muçarela, uma porção de carne e enrole.",
        "Faça esse processo com todas as panquecas.",
        "Despeje um pouco de caldo no fundo de um refratário, para untar.",
        "Disponha as panquecas já prontas no refratário e despeje sobre elas o restante do molho.",
        "Polvilhe queijo ralado sobre as panquecas.",
        "Leve ao forno para gratinar, em fogo médio, por 20 minutos ou até que o queijo esteja derretido.",
      ],
      "INFORMAÇÕES ADICIONAIS": [
        "Panqueca é uma daquelas receitas perfeitas para quem procura um almoço prático, que sustente e que seja saboroso! Com ótimo rendimento, elas levam apenas ingredientes básicos, que você tem aí na sua casa, para serem feitas. Além da massa de panqueca que por si só é deliciosa, o prato também agrada por suas infinitas possibilidades de recheio. Seja você um masterchef ou um aventureiro de primeira viagem, aprenda como é fácil fazer uma deliciosa receita de panqueca! Afinal de contas, a base precisa ser boa para a receita ficar gostosa, né?\nDurante o processo, use uma frigideira antiaderente. Isso vai garantir o sucesso da sua panqueca de carne moída, para que ela não grude e nem rasgue. Além disso, entre uma concha de massa e outra, verifique se o fundo precisa de mais óleo. Ele também faz com quem a massa da panqueca deslize com mais facilidade e fique perfeita. \nSabia que essa massa também spode ser usada para panquecas doces? Basta substituir o sal por açúcar e fazer o recheio de frutas, doces e chocolates. Use sua criatividade!\nEsqueceu de comprar a farinha de trigo ou o que sobrou da última receita é muito pouco? Calma que temos a solução! Que tal substituir a farinha de trigo por amido de milho? Sua panqueca ficará mais leve e ainda mais fofinha. Confira a receita completa!\nE se você gosta do preparo de massas no geral, conheça mais receitas deliciosas do site! Aqui no TudoGostoso você pode aprender a fazer macarrão de forno, lasanha de massa de panqueca, macarrão à bolonhesa e ravióli de abóbora. \nConfira mais receitas com carne incríveis: strogonoff de carne, rocambole de carne moída, bife à rolê, escondidinho de carne moída, polenta com carne moída, bife de panela de pressão, picanha ao forno com sal grosso e mais delícias!\nVeja também as nossas deliciosas receitas com carneiro!\nVeja outras dicas e receitas no blog do TudoGostoso:\nReceitas com massa da lasanha: 25 opções fáceis de fazer\nMassa: confira receitas deliciosas e fáceis de fazer",
      ],
    },
    tempo_de_preparo: "40 MIN",
    rendimento: "10 PORÇÕES",
    autor: "DANIEL SOBERAS",
    url_receita:
      "https://www.tudogostoso.com.br/receita/760-panqueca-de-carne-moida.html",
  },
];
